// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"net/http"
	"strings"
)

// Proj4APIController binds http requests to an api service and writes the service results to the http response
type Proj4APIController struct {
	service      Proj4APIServicer
	errorHandler ErrorHandler
}

// Proj4APIOption for how the controller is set up.
type Proj4APIOption func(*Proj4APIController)

// WithProj4APIErrorHandler inject ErrorHandler into controller
func WithProj4APIErrorHandler(h ErrorHandler) Proj4APIOption {
	return func(c *Proj4APIController) {
		c.errorHandler = h
	}
}

// NewProj4APIController creates a default api controller
func NewProj4APIController(s Proj4APIServicer, opts ...Proj4APIOption) *Proj4APIController {
	controller := &Proj4APIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the Proj4APIController
func (c *Proj4APIController) Routes() Routes {
	return Routes{
		"GetQueries": Route{
			"GetQueries",
			strings.ToUpper("Get"),
			"/queries",
			c.GetQueries,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the Proj4APIController
func (c *Proj4APIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetQueries",
			strings.ToUpper("Get"),
			"/queries",
			c.GetQueries,
		},
	}
}

// GetQueries - Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
func (c *Proj4APIController) GetQueries(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetQueries(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
