// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"net/http"
	"time"
)

// MetadataAPIService is a service that implements the logic for the MetadataAPIServicer
// This service should implement the business logic for every endpoint for the MetadataAPI API.
// Include any external packages or services that will be required by this service.
type MetadataAPIService struct {
	startTime int64
}

// NewMetadataAPIService creates a default api service
func NewMetadataAPIService() *MetadataAPIService {
	return &MetadataAPIService{startTime: time.Now().Unix()}
}

// GetSystemInfo - Get basic information about the system (e.g. version, uptime, etc.)
func (s *MetadataAPIService) GetSystemInfo(ctx context.Context) (ImplResponse, error) {

	sysInfo := SystemInformation{
		Author:           "Tomasz Głąb",
		Version:          "Lab3.0.0",
		InterfaceVersion: "1.0.1",
		Uptime:           time.Now().Unix() - s.startTime,
	}
	return Response(http.StatusOK, sysInfo), nil
}
