// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ExecutionAPIService is a service that implements the logic for the ExecutionAPIServicer
// This service should implement the business logic for every endpoint for the ExecutionAPI API.
// Include any external packages or services that will be required by this service.
type ExecutionAPIService struct {
}

// NewExecutionAPIService creates a default api service
func NewExecutionAPIService() *ExecutionAPIService {
	return &ExecutionAPIService{}
}

// GetQueries - Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
func (s *ExecutionAPIService) GetQueries(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetQueries with the required logic for this service method.
	// Add api_execution_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ShallowQuery{}) or use other options such as http.Ok ...
	// return Response(200, []ShallowQuery{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueries method not implemented")
}

// GetQueryById - Get detailed status of selected query
func (s *ExecutionAPIService) GetQueryById(ctx context.Context, queryId string) (ImplResponse, error) {
	// TODO - update GetQueryById with the required logic for this service method.
	// Add api_execution_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Query{}) or use other options such as http.Ok ...
	// return Response(200, Query{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryById method not implemented")
}

// SubmitQuery - Submit new query for execution
func (s *ExecutionAPIService) SubmitQuery(ctx context.Context, executeQueryRequest ExecuteQueryRequest) (ImplResponse, error) {
	// TODO - update SubmitQuery with the required logic for this service method.
	// Add api_execution_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	// return Response(200, string{}), nil

	// TODO: Uncomment the next line to return response Response(400, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(400, MultipleProblemsError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SubmitQuery method not implemented")
}

// GetQueryResult - Get result of selected query (will be available only for SELECT queries after they are completed)
func (s *ExecutionAPIService) GetQueryResult(ctx context.Context, queryId string, getQueryResultRequest GetQueryResultRequest) (ImplResponse, error) {
	// TODO - update GetQueryResult with the required logic for this service method.
	// Add api_execution_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []QueryResultInner{}) or use other options such as http.Ok ...
	// return Response(200, []QueryResultInner{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryResult method not implemented")
}

// GetQueryError - Get error of selected query (will be available only for queries in FAILED state)
func (s *ExecutionAPIService) GetQueryError(ctx context.Context, queryId string) (ImplResponse, error) {
	// TODO - update GetQueryError with the required logic for this service method.
	// Add api_execution_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(200, MultipleProblemsError{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryError method not implemented")
}
