// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// Proj3APIService is a service that implements the logic for the Proj3APIServicer
// This service should implement the business logic for every endpoint for the Proj3API API.
// Include any external packages or services that will be required by this service.
type Proj3APIService struct {
}

// NewProj3APIService creates a default api service
func NewProj3APIService() *Proj3APIService {
	return &Proj3APIService{}
}

// GetTables - Get list of tables with their accompanying IDs. Use those IDs to get details by calling /table endpoint.
func (s *Proj3APIService) GetTables(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTables with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ShallowTable{}) or use other options such as http.Ok ...
	// return Response(200, []ShallowTable{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTables method not implemented")
}

// GetTableById - Get detailed description of selected table
func (s *Proj3APIService) GetTableById(ctx context.Context, tableId string) (ImplResponse, error) {
	// TODO - update GetTableById with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, TableSchema{}) or use other options such as http.Ok ...
	// return Response(200, TableSchema{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTableById method not implemented")
}

// DeleteTable - Delete selected table from database
func (s *Proj3APIService) DeleteTable(ctx context.Context, tableId string) (ImplResponse, error) {
	// TODO - update DeleteTable with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTable method not implemented")
}

// CreateTable - Create new table in database
func (s *Proj3APIService) CreateTable(ctx context.Context, tableSchema TableSchema) (ImplResponse, error) {
	// TODO - update CreateTable with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	// return Response(200, string{}), nil

	// TODO: Uncomment the next line to return response Response(400, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(400, MultipleProblemsError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTable method not implemented")
}

// GetQueries - Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
func (s *Proj3APIService) GetQueries(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetQueries with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ShallowQuery{}) or use other options such as http.Ok ...
	// return Response(200, []ShallowQuery{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueries method not implemented")
}

// GetQueryById - Get detailed status of selected query
func (s *Proj3APIService) GetQueryById(ctx context.Context, queryId string) (ImplResponse, error) {
	// TODO - update GetQueryById with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Query{}) or use other options such as http.Ok ...
	// return Response(200, Query{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryById method not implemented")
}

// SubmitQuery - Submit new query for execution
func (s *Proj3APIService) SubmitQuery(ctx context.Context, executeQueryRequest ExecuteQueryRequest) (ImplResponse, error) {
	// TODO - update SubmitQuery with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	// return Response(200, string{}), nil

	// TODO: Uncomment the next line to return response Response(400, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(400, MultipleProblemsError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SubmitQuery method not implemented")
}

// GetQueryResult - Get result of selected query (will be available only for SELECT queries after they are completed)
func (s *Proj3APIService) GetQueryResult(ctx context.Context, queryId string, getQueryResultRequest GetQueryResultRequest) (ImplResponse, error) {
	// TODO - update GetQueryResult with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []QueryResultInner{}) or use other options such as http.Ok ...
	// return Response(200, []QueryResultInner{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryResult method not implemented")
}

// GetQueryError - Get error of selected query (will be available only for queries in FAILED state)
func (s *Proj3APIService) GetQueryError(ctx context.Context, queryId string) (ImplResponse, error) {
	// TODO - update GetQueryError with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, MultipleProblemsError{}) or use other options such as http.Ok ...
	// return Response(200, MultipleProblemsError{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueryError method not implemented")
}

// GetSystemInfo - Get basic information about the system (e.g. version, uptime, etc.)
func (s *Proj3APIService) GetSystemInfo(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetSystemInfo with the required logic for this service method.
	// Add api_proj3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SystemInformation{}) or use other options such as http.Ok ...
	// return Response(200, SystemInformation{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSystemInfo method not implemented")
}
