// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"net/http"
	"strings"
)

// MetadataAPIController binds http requests to an api service and writes the service results to the http response
type MetadataAPIController struct {
	service      MetadataAPIServicer
	errorHandler ErrorHandler
}

// MetadataAPIOption for how the controller is set up.
type MetadataAPIOption func(*MetadataAPIController)

// WithMetadataAPIErrorHandler inject ErrorHandler into controller
func WithMetadataAPIErrorHandler(h ErrorHandler) MetadataAPIOption {
	return func(c *MetadataAPIController) {
		c.errorHandler = h
	}
}

// NewMetadataAPIController creates a default api controller
func NewMetadataAPIController(s MetadataAPIServicer, opts ...MetadataAPIOption) *MetadataAPIController {
	controller := &MetadataAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MetadataAPIController
func (c *MetadataAPIController) Routes() Routes {
	return Routes{
		"GetSystemInfo": Route{
			"GetSystemInfo",
			strings.ToUpper("Get"),
			"/system/info",
			c.GetSystemInfo,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the MetadataAPIController
func (c *MetadataAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetSystemInfo",
			strings.ToUpper("Get"),
			"/system/info",
			c.GetSystemInfo,
		},
	}
}

// GetSystemInfo - Get basic information about the system (e.g. version, uptime, etc.)
func (c *MetadataAPIController) GetSystemInfo(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetSystemInfo(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
