// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// MetadataAPIService is a service that implements the logic for the MetadataAPIServicer
// This service should implement the business logic for every endpoint for the MetadataAPI API.
// Include any external packages or services that will be required by this service.
type MetadataAPIService struct {
}

// NewMetadataAPIService creates a default api service
func NewMetadataAPIService() *MetadataAPIService {
	return &MetadataAPIService{}
}

// GetSystemInfo - Get basic information about the system (e.g. version, uptime, etc.)
func (s *MetadataAPIService) GetSystemInfo(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetSystemInfo with the required logic for this service method.
	// Add api_metadata_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SystemInformation{}) or use other options such as http.Ok ...
	// return Response(200, SystemInformation{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSystemInfo method not implemented")
}
