// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// Proj4APIService is a service that implements the logic for the Proj4APIServicer
// This service should implement the business logic for every endpoint for the Proj4API API.
// Include any external packages or services that will be required by this service.
type Proj4APIService struct {
}

// NewProj4APIService creates a default api service
func NewProj4APIService() *Proj4APIService {
	return &Proj4APIService{}
}

// GetQueries - Get list of queries (optional in project 3, but useful). Use those IDs to get details by calling /query endpoint.
func (s *Proj4APIService) GetQueries(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetQueries with the required logic for this service method.
	// Add api_proj4_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []ShallowQuery{}) or use other options such as http.Ok ...
	// return Response(200, []ShallowQuery{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetQueries method not implemented")
}
