// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// Function - Description of a function used in column expression
type Function struct {
	FunctionName string `json:"functionName,omitempty"`

	Arguments []ColumnExpression `json:"arguments,omitempty"`
}

// AssertFunctionRequired checks if the required fields are not zero-ed
func AssertFunctionRequired(obj Function) error {
	for _, el := range obj.Arguments {
		if err := AssertColumnExpressionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertFunctionConstraints checks if the values respects the defined constraints
func AssertFunctionConstraints(obj Function) error {
	for _, el := range obj.Arguments {
		if err := AssertColumnExpressionConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
