// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// LimitExpression - Description of LIMIT clause in SELECT query
type LimitExpression struct {
	Limit int32 `json:"limit,omitempty"`
}

// AssertLimitExpressionRequired checks if the required fields are not zero-ed
func AssertLimitExpressionRequired(obj LimitExpression) error {
	return nil
}

// AssertLimitExpressionConstraints checks if the values respects the defined constraints
func AssertLimitExpressionConstraints(obj LimitExpression) error {
	return nil
}
