// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

import (
	"encoding/json"
)

type LiteralValue struct {
	Data interface{}
}

func (l *LiteralValue) UnmarshalJSON(b []byte) error {
	var v interface{}
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	if f, ok := v.(float64); ok {
		if float64(int64(f)) == f {
			l.Data = int64(f)
			return nil
		}
	}
	l.Data = v
	return nil
}

func (l LiteralValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(l.Data)
}

// AssertLiteralValueRequired checks if the required fields are not zero-ed
func AssertLiteralValueRequired(obj LiteralValue) error {
	return nil
}

// AssertLiteralValueConstraints checks if the values respects the defined constraints
func AssertLiteralValueConstraints(obj LiteralValue) error {
	return nil
}
