// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// OrderByExpression - Description of ORDER BY clause in SELECT query
type OrderByExpression struct {

	// Index of the column from the columnClauses (0-based). We can Assume that ordering is done only on data that are results of the query.
	ColumnIndex int32 `json:"columnIndex,omitempty"`

	Ascending bool `json:"ascending,omitempty"`
}

// AssertOrderByExpressionRequired checks if the required fields are not zero-ed
func AssertOrderByExpressionRequired(obj OrderByExpression) error {
	return nil
}

// AssertOrderByExpressionConstraints checks if the values respects the defined constraints
func AssertOrderByExpressionConstraints(obj OrderByExpression) error {
	return nil
}
