// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// ColumnReferenceExpression - Description of a reference to a column used in column expression
type ColumnReferenceExpression struct {
	TableName string `json:"tableName,omitempty"`

	ColumnName string `json:"columnName,omitempty"`
}

// AssertColumnReferenceExpressionRequired checks if the required fields are not zero-ed
func AssertColumnReferenceExpressionRequired(obj ColumnReferenceExpression) error {
	return nil
}

// AssertColumnReferenceExpressionConstraints checks if the values respects the defined constraints
func AssertColumnReferenceExpressionConstraints(obj ColumnReferenceExpression) error {
	return nil
}
