// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// ColumnarBinaryOperation - Description of columnar operator used in column expression
type ColumnarBinaryOperation struct {
	Operator string `json:"operator,omitempty"`

	LeftOperand ColumnExpression `json:"leftOperand,omitempty"`

	RightOperand ColumnExpression `json:"rightOperand,omitempty"`
}

// AssertColumnarBinaryOperationRequired checks if the required fields are not zero-ed
func AssertColumnarBinaryOperationRequired(obj ColumnarBinaryOperation) error {
	if err := AssertColumnExpressionRequired(obj.LeftOperand); err != nil {
		return err
	}
	if err := AssertColumnExpressionRequired(obj.RightOperand); err != nil {
		return err
	}
	return nil
}

// AssertColumnarBinaryOperationConstraints checks if the values respects the defined constraints
func AssertColumnarBinaryOperationConstraints(obj ColumnarBinaryOperation) error {
	if err := AssertColumnExpressionConstraints(obj.LeftOperand); err != nil {
		return err
	}
	if err := AssertColumnExpressionConstraints(obj.RightOperand); err != nil {
		return err
	}
	return nil
}
