// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// Literal - Description of a literal value used in column expression
type Literal struct {
	Value LiteralValue `json:"value,omitempty"`
}

// AssertLiteralRequired checks if the required fields are not zero-ed
func AssertLiteralRequired(obj Literal) error {
	if err := AssertLiteralValueRequired(obj.Value); err != nil {
		return err
	}
	return nil
}

// AssertLiteralConstraints checks if the values respects the defined constraints
func AssertLiteralConstraints(obj Literal) error {
	if err := AssertLiteralValueConstraints(obj.Value); err != nil {
		return err
	}
	return nil
}
