// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// SelectQuery - Description of a select query
type SelectQuery struct {
	ColumnClauses []ColumnExpression `json:"columnClauses"`

	WhereClause ColumnExpression `json:"whereClause,omitempty"`

	OrderByClause []OrderByExpression `json:"orderByClause,omitempty"`

	LimitClause *LimitExpression `json:"limitClause,omitempty"`
}

// AssertSelectQueryRequired checks if the required fields are not zero-ed
func AssertSelectQueryRequired(obj SelectQuery) error {
	elements := map[string]interface{}{
		"columnClauses": obj.ColumnClauses,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.ColumnClauses {
		if err := AssertColumnExpressionRequired(el); err != nil {
			return err
		}
	}
	if obj.WhereClause.Expression != nil {
		if err := AssertColumnExpressionRequired(obj.WhereClause); err != nil {
			return err
		}
	}
	for _, el := range obj.OrderByClause {
		if err := AssertOrderByExpressionRequired(el); err != nil {
			return err
		}
	}
	if obj.LimitClause != nil {
		if err := AssertLimitExpressionRequired(*obj.LimitClause); err != nil {
			return err
		}
	}
	return nil
}

// AssertSelectQueryConstraints checks if the values respects the defined constraints
func AssertSelectQueryConstraints(obj SelectQuery) error {
	for _, el := range obj.ColumnClauses {
		if err := AssertColumnExpressionConstraints(el); err != nil {
			return err
		}
	}
	if obj.WhereClause.Expression != nil {
		if err := AssertColumnExpressionConstraints(obj.WhereClause); err != nil {
			return err
		}
	}
	for _, el := range obj.OrderByClause {
		if err := AssertOrderByExpressionConstraints(el); err != nil {
			return err
		}
	}
	if obj.LimitClause != nil {
		if err := AssertLimitExpressionConstraints(*obj.LimitClause); err != nil {
			return err
		}
	}
	return nil
}
