// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package openapi

// ColumnarUnaryOperation - Description of unary Operation
type ColumnarUnaryOperation struct {
	Operand ColumnExpression `json:"operand,omitempty"`

	Operator string `json:"operator,omitempty"`
}

// AssertColumnarUnaryOperationRequired checks if the required fields are not zero-ed
func AssertColumnarUnaryOperationRequired(obj ColumnarUnaryOperation) error {
	if err := AssertColumnExpressionRequired(obj.Operand); err != nil {
		return err
	}
	return nil
}

// AssertColumnarUnaryOperationConstraints checks if the values respects the defined constraints
func AssertColumnarUnaryOperationConstraints(obj ColumnarUnaryOperation) error {
	if err := AssertColumnExpressionConstraints(obj.Operand); err != nil {
		return err
	}
	return nil
}
