// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package main

import (
	"log"
	"net/http"

	openapi "isbd3/go"
	"isbd3/pkg/engine"
	"isbd3/pkg/metadata"
)

func main() {
	log.Printf("Server started")
	dbmsBaseDir := ".dbms_data"
	metastore := metadata.NewMetastore(dbmsBaseDir)

	queryManager := engine.NewQueryManager(metastore, dbmsBaseDir)

	ExecutionAPIService := openapi.NewExecutionAPIService(queryManager)
	ExecutionAPIController := openapi.NewExecutionAPIController(ExecutionAPIService)

	MetadataAPIService := openapi.NewMetadataAPIService()
	MetadataAPIController := openapi.NewMetadataAPIController(MetadataAPIService)

	SchemaAPIService := openapi.NewSchemaAPIService(metastore)
	SchemaAPIController := openapi.NewSchemaAPIController(SchemaAPIService)

	router := openapi.NewRouter(ExecutionAPIController, MetadataAPIController, SchemaAPIController)

	// Required for Swagger UI
	router.PathPrefix("/api/").Handler(http.StripPrefix("/api/", http.FileServer(http.Dir("./api"))))

	router.HandleFunc("/swagger", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./api/index.html")
	})
	log.Printf("Try it out at http://localhost:8080/swagger")

	log.Fatal(http.ListenAndServe(":8080", router))
}
