// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 1.0.1
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ExecutionAPIService := openapi.NewExecutionAPIService()
	ExecutionAPIController := openapi.NewExecutionAPIController(ExecutionAPIService)

	MetadataAPIService := openapi.NewMetadataAPIService()
	MetadataAPIController := openapi.NewMetadataAPIController(MetadataAPIService)

	Proj3APIService := openapi.NewProj3APIService()
	Proj3APIController := openapi.NewProj3APIController(Proj3APIService)

	Proj4APIService := openapi.NewProj4APIService()
	Proj4APIController := openapi.NewProj4APIController(Proj4APIService)

	SchemaAPIService := openapi.NewSchemaAPIService()
	SchemaAPIController := openapi.NewSchemaAPIController(SchemaAPIService)

	router := openapi.NewRouter(ExecutionAPIController, MetadataAPIController, Proj3APIController, Proj4APIController, SchemaAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
