// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * MIMUW ISBD database system
 *
 * This file describes interface between DBMS system and user.
 *
 * API version: 2.1.0
 */

package main

import (
	"log"
	"net/http"

	"isbd4/openapi"
	"isbd4/pkg/engine"
	"isbd4/pkg/metadata"
	"isbd4/pkg/service"
)

func main() {
	log.Printf("Server started")
	dbmsBaseDir := ".dbms_data"
	chunkSize := uint64(1000)
	maxRowsInFile := uint64(10000)
	memoryLimitBytes := uint64(10 * 1024 * 1024) // 10MB default

	metastore := metadata.NewMetastore(dbmsBaseDir)

	queryManager := engine.NewQueryManager(metastore, dbmsBaseDir, chunkSize, maxRowsInFile, memoryLimitBytes)

	ExecutionAPIService := service.NewExecutionAPIService(queryManager)
	ExecutionAPIController := openapi.NewExecutionAPIController(ExecutionAPIService)

	MetadataAPIService := service.NewMetadataAPIService()
	MetadataAPIController := openapi.NewMetadataAPIController(MetadataAPIService)

	SchemaAPIService := service.NewSchemaAPIService(metastore)
	SchemaAPIController := openapi.NewSchemaAPIController(SchemaAPIService)

	router := openapi.NewRouter(ExecutionAPIController, MetadataAPIController, SchemaAPIController)

	// Required for Swagger UI
	router.PathPrefix("/api/").Handler(http.StripPrefix("/api/", http.FileServer(http.Dir("./api"))))

	router.HandleFunc("/swagger", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./api/index.html")
	})
	log.Printf("Try it out at http://localhost:8080/swagger")

	log.Fatal(http.ListenAndServe(":8080", router))
}
